### ISSUE TITLE
Ubuntu 20.04 pip installation failure

### ISSUE THREAD

**Issue by xanmankey** [LeeKamentsky/python-javabridge#202]
Hi there! Before I get into the meat and potatoes of my question, I want to preface it by saying that this is my first time filing an issue on Github, so let me know if you need any more information, if anything comes across as unclear, or if there is somewhere else I should be asking about this.

I've been using `python-weka-wrapper3` for a python module (the source code can be found here: https://github.com/xanmankey/FishingForPhish) to help automate and aid research on phishing-detection, and it depends on `python-javabridge`. However, I've been having inconsistent success with installing `python-javabridge` via pip, and I was hoping someone could help me out. I was able to install the library once by running the command `pip install git+https://github.com/LeeKamentsky/python-javabridge.git@master` in a venv, but haven't been able to replicate that installation since, and in order to distribute via pypi I would need a consistent installation method (at least for Ubuntu, I haven't had time to test other OS). The compiler output using Ubuntu 20.04, Python 3.10.2, the latest version of pip, and JDK and JRE 17.0.2
for both `pip install git+https://github.com/LeeKamentsky/python-javabridge.git@master` and `pip install python-javabridge` can be found below. I tried installing using both the oldest supported version of numpy and the latest version of numpy, but the error is the same either way.

> (venv) /workspaces/myStuff/ $ pip install python-javabridge
Collecting python-javabridge
  Downloading python-javabridge-4.0.3.tar.gz (1.3 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.3/1.3 MB 125.1 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... done
Requirement already satisfied: numpy>=1.20.1 in ./venv/lib/python3.10/site-packages (from python-javabridge) (1.22.3)
Building wheels for collected packages: python-javabridge
  Building wheel for python-javabridge (setup.py) ... error
  error: subprocess-exited-with-error
 × python setup.py bdist_wheel did not run successfully.
  │ exit code: 1
  ╰─> [49 lines of output]
      running bdist_wheel
      running build
      running build_py
      creating build
      creating build/lib.linux-x86_64-3.10
      creating build/lib.linux-x86_64-3.10/javabridge
      copying javabridge/wrappers.py -> build/lib.linux-x86_64-3.10/javabridge
      copying javabridge/locate.py -> build/lib.linux-x86_64-3.10/javabridge
      copying javabridge/noseplugin.py -> build/lib.linux-x86_64-3.10/javabridge
      copying javabridge/__init__.py -> build/lib.linux-x86_64-3.10/javabridge
      copying javabridge/jutil.py -> build/lib.linux-x86_64-3.10/javabridge
      creating build/lib.linux-x86_64-3.10/javabridge/tests
      copying javabridge/tests/test_cpython.py -> build/lib.linux-x86_64-3.10/javabridge/tests
      copying javabridge/tests/test_javabridge.py -> build/lib.linux-x86_64-3.10/javabridge/tests
      copying javabridge/tests/__init__.py -> build/lib.linux-x86_64-3.10/javabridge/tests
      copying javabridge/tests/test_jutil.py -> build/lib.linux-x86_64-3.10/javabridge/tests
      copying javabridge/tests/test_wrappers.py -> build/lib.linux-x86_64-3.10/javabridge/tests
      creating build/lib.linux-x86_64-3.10/javabridge/jars
      copying javabridge/jars/test.jar -> build/lib.linux-x86_64-3.10/javabridge/jars
      copying javabridge/jars/rhino-1.7R4.jar -> build/lib.linux-x86_64-3.10/javabridge/jars
      copying javabridge/jars/runnablequeue.jar -> build/lib.linux-x86_64-3.10/javabridge/jars
      copying javabridge/jars/cpython.jar -> build/lib.linux-x86_64-3.10/javabridge/jars
      warning: build_py: byte-compiling is disabled, skipping.     
      running build_ext
      javac -source 8 -target 8 /tmp/pip-install-nro4vrdx/python-javabridge_14dd9b8273e94c34b0006bc516fdefed/java/org/cellprofiler/runnablequeue/RunnableQueue.java
      warning: [options] bootstrap class path not set in conjunction with -source 8
      1 warning
      javac -source 8 -target 8 /tmp/pip-install-nro4vrdx/python-javabridge_14dd9b8273e94c34b0006bc516fdefed/java/org/cellprofiler/javabridge/test/RealRect.java
      warning: [options] bootstrap class path not set in conjunction with -source 8
      1 warning
      javac -source 8 -target 8 /tmp/pip-install-nro4vrdx/python-javabridge_14dd9b8273e94c34b0006bc516fdefed/java/org/cellprofiler/javabridge/CPython.java /tmp/pip-install-nro4vrdx/python-javabridge_14dd9b8273e94c34b0006bc516fdefed/java/org/cellprofiler/javabridge/CPythonInvocationHandler.java
      warning: [options] bootstrap class path not set in conjunction with -source 8
      Note: /tmp/pip-install-nro4vrdx/python-javabridge_14dd9b8273e94c34b0006bc516fdefed/java/org/cellprofiler/javabridge/CPythonInvocationHandler.java uses unchecked or unsafe operations.
      Note: Recompile with -Xlint:unchecked for details.
      1 warning
      building 'javabridge._javabridge' extension
      creating build/temp.linux-x86_64-3.10
      clang -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -ferror-limit=1 -ggdb3 -O0 -std=c11 -Wall -Werror -Wextra -Wno-sign-compare -Wno-unused-parameter -Wno-unused-variable -Wshadow -fPIC -I/workspaces/myStuff/venv/lib/python3.10/site-packages/numpy/core/include -I/usr/lib/jvm/java-17-oracle/include -I/usr/lib/jvm/java-17-oracle/include/linux -I/usr/lib/jvm/java-17-oracle/default-java/include -I/usr/lib/jvm/java-17-oracle/default-java/include/linux -I/workspaces/myStuff/venv/lib/python3.10/site-packages/numpy/core/include -I/workspaces/myStuff/venv/include -I/usr/local/include/python3.10 -c _javabridge.c -o build/temp.linux-x86_64-3.10/_javabridge.o
      In file included from _javabridge.c:610:
      In file included from /workspaces/myStuff/venv/lib/python3.10/site-packages/numpy/core/include/numpy/arrayobject.h:5:
      In file included from /workspaces/myStuff/venv/lib/python3.10/site-packages/numpy/core/include/numpy/ndarrayobject.h:12:
      In file included from /workspaces/myStuff/venv/lib/python3.10/site-packages/numpy/core/include/numpy/ndarraytypes.h:1960:
      /workspaces/myStuff/venv/lib/python3.10/site-packages/numpy/core/include/numpy/npy_1_7_deprecated_api.h:17:2: error: "Using deprecated NumPy API, disable it with "          "#define NPY_NO_DEPRECATED_API NPY_1_7_API_VERSION" [-Werror,-W#warnings]
      #warning "Using deprecated NumPy API, disable it with " \
       ^
      fatal error: too many errors emitted, stopping now [-ferror-limit=]
      2 errors generated.
      error: command '/usr/bin/clang' failed with exit code 1
      [end of output] 
  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for python-javabridge
  Running setup.py clean for python-javabridge
Failed to build python-javabridge
Installing collected packages: python-javabridge
  Running setup.py install for python-javabridge ... error
  error: subprocess-exited-with-error 
  × Running setup.py install for python-javabridge did not run successfully.
  │ exit code: 1
  ╰─> [49 lines of output]
      running install
      running build
      running build_py
      creating build
      creating build/lib.linux-x86_64-3.10
      creating build/lib.linux-x86_64-3.10/javabridge
      copying javabridge/wrappers.py -> build/lib.linux-x86_64-3.10/javabridge
      copying javabridge/locate.py -> build/lib.linux-x86_64-3.10/javabridge
      copying javabridge/noseplugin.py -> build/lib.linux-x86_64-3.10/javabridge
      copying javabridge/__init__.py -> build/lib.linux-x86_64-3.10/javabridge
      copying javabridge/jutil.py -> build/lib.linux-x86_64-3.10/javabridge
      creating build/lib.linux-x86_64-3.10/javabridge/tests
      copying javabridge/tests/test_cpython.py -> build/lib.linux-x86_64-3.10/javabridge/tests
      copying javabridge/tests/test_javabridge.py -> build/lib.linux-x86_64-3.10/javabridge/tests
      copying javabridge/tests/__init__.py -> build/lib.linux-x86_64-3.10/javabridge/tests
      copying javabridge/tests/test_jutil.py -> build/lib.linux-x86_64-3.10/javabridge/tests
      copying javabridge/tests/test_wrappers.py -> build/lib.linux-x86_64-3.10/javabridge/tests
      creating build/lib.linux-x86_64-3.10/javabridge/jars
      copying javabridge/jars/test.jar -> build/lib.linux-x86_64-3.10/javabridge/jars
      copying javabridge/jars/rhino-1.7R4.jar -> build/lib.linux-x86_64-3.10/javabridge/jars
      copying javabridge/jars/runnablequeue.jar -> build/lib.linux-x86_64-3.10/javabridge/jars
      copying javabridge/jars/cpython.jar -> build/lib.linux-x86_64-3.10/javabridge/jars
      warning: build_py: byte-compiling is disabled, skipping.    
      running build_ext
      javac -source 8 -target 8 /tmp/pip-install-nro4vrdx/python-javabridge_14dd9b8273e94c34b0006bc516fdefed/java/org/cellprofiler/runnablequeue/RunnableQueue.java
      warning: [options] bootstrap class path not set in conjunction with -source 8
      1 warning
      javac -source 8 -target 8 /tmp/pip-install-nro4vrdx/python-javabridge_14dd9b8273e94c34b0006bc516fdefed/java/org/cellprofiler/javabridge/test/RealRect.java
      warning: [options] bootstrap class path not set in conjunction with -source 8
      1 warning
      javac -source 8 -target 8 /tmp/pip-install-nro4vrdx/python-javabridge_14dd9b8273e94c34b0006bc516fdefed/java/org/cellprofiler/javabridge/CPython.java /tmp/pip-install-nro4vrdx/python-javabridge_14dd9b8273e94c34b0006bc516fdefed/java/org/cellprofiler/javabridge/CPythonInvocationHandler.java
      warning: [options] bootstrap class path not set in conjunction with -source 8
      Note: /tmp/pip-install-nro4vrdx/python-javabridge_14dd9b8273e94c34b0006bc516fdefed/java/org/cellprofiler/javabridge/CPythonInvocationHandler.java uses unchecked or unsafe operations.
      Note: Recompile with -Xlint:unchecked for details.
      1 warning
      building 'javabridge._javabridge' extension
      creating build/temp.linux-x86_64-3.10
      clang -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -ferror-limit=1 -ggdb3 -O0 -std=c11 -Wall -Werror -Wextra -Wno-sign-compare -Wno-unused-parameter -Wno-unused-variable -Wshadow -fPIC -I/workspaces/myStuff/venv/lib/python3.10/site-packages/numpy/core/include -I/usr/lib/jvm/java-17-oracle/include -I/usr/lib/jvm/java-17-oracle/include/linux -I/usr/lib/jvm/java-17-oracle/default-java/include -I/usr/lib/jvm/java-17-oracle/default-java/include/linux -I/workspaces/myStuff/venv/lib/python3.10/site-packages/numpy/core/include -I/workspaces/myStuff/venv/include -I/usr/local/include/python3.10 -c _javabridge.c -o build/temp.linux-x86_64-3.10/_javabridge.o
      In file included from _javabridge.c:610:
      In file included from /workspaces/myStuff/venv/lib/python3.10/site-packages/numpy/core/include/numpy/arrayobject.h:5:
      In file included from /workspaces/myStuff/venv/lib/python3.10/site-packages/numpy/core/include/numpy/ndarrayobject.h:12:
      In file included from /workspaces/myStuff/venv/lib/python3.10/site-packages/numpy/core/include/numpy/ndarraytypes.h:1960:
      /workspaces/myStuff/venv/lib/python3.10/site-packages/numpy/core/include/numpy/npy_1_7_deprecated_api.h:17:2: error: "Using deprecated NumPy API, disable it with "          "#define NPY_NO_DEPRECATED_API NPY_1_7_API_VERSION" [-Werror,-W#warnings]
      #warning "Using deprecated NumPy API, disable it with " \
       ^
      fatal error: too many errors emitted, stopping now [-ferror-limit=]
      2 errors generated.
      error: command '/usr/bin/clang' failed with exit code 1
      [end of output]
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: legacy-install-failure
× Encountered error while trying to install package.
╰─> python-javabridge
note: This is an issue with the package mentioned above, not pip.
hint: See above for output from the failure.

**Comment by xanmankey** [comment]
A bit of a follow up:

I have two environments I commonly code in: VS Codespaces (which I think is an online docker container) and VS Code on a WSL build. It turns out that when I run `pip install python-javabridge` on my WSL build `python-javabridge` installs without a hitch. I don't know why that wouldn't be the case for VS Codespaces though, my best guess is either the discrepancy in OpenJDK + JRE version (11.0.14.1 on my WSL build) or the python version (I was able to install it on my WSL build using 3.8.10). I imagine the root of the problem comes from something I'm missing regarding the installation process (are there any version requirements that I'm failing; if so, it hasn't been immediately obvious to me) or an issue with docker containers (I don't know much about them, but from what I do know that seems unlikely). I tried replicating the installation with version 3.8.10 of python and that failed with the same error, and it doesn't seem like the problem relates to the JDK + JRE, so I still have yet to try version 11.0.14.1.

**Comment by xanmankey** [comment]
I found another discrepancy that I think might be related to the issue: when I run sudo update-alternatives --config java, the only version 17 output option is */usr/lib/jvm/java-17-oracle/bin/java*, which differs from the format of the other versions (for example */usr/lib/jvm/java-11-openjdk-amd64/bin/java*). I'm not quite sure what the difference is (I'm very new to java) but it could be the cause of the issue, I'll experiment when I have time.

**Comment by LeeKamentsky** [comment]
I'm sorry, I've lost control of the PIP account and haven't had much luck
getting it reinstated. The only way to install the latest is from github
the way you did. That seems to work fine still on Ubuntu.
- Lee
(he, him, his)

**Comment by xanmankey** [comment]
Yep, it definitely still works fine on my ubuntu machine (`pip install python-javabridge` actually works as well on my Ubuntu machine, but installing using pypi and the github in Codespaces, even after experimenting with a couple of different JDK and JRE versions and python versions still fails, I'm not sure why). On another note, I've been trying to compact the dependency installation process into one step (specifically because I've been trying to deploy a flask app to vercel and from my knowledge, vercel builds dependencies from requirements.txt in one step), but when trying to install from requirements.txt I always get a `ModuleNotFoundError` regarding numpy (numpy seems to be a build dependency of python-javabridge). I'm wondering if there's a way to avoid this besides installing numpy prior to the installation? 

(I'm also wondering if I'm just missing something regarding environment problems in general, because with Ubuntu I can install from requirements.txt even without installing numpy first; I'm not sure why I'm getting ModuleNotFoundError in the context of Vercel, that might be something I need to take up with them, or look into some requirements.txt and pip installation hacks for, but I figured since I was already here I might as well try asking).

Compiler error:
> Failed to run "pip3.9 install --disable-pip-version-check --target . --upgrade -r /vercel/path0/requirements.txt"
--
10:28:01.844 | Error: Command failed: pip3.9 install --disable-pip-version-check --target . --upgrade -r /vercel/path0/requirements.txt
10:28:01.844 | error: subprocess-exited-with-error
10:28:01.844 |  
10:28:01.845 | × python setup.py egg_info did not run successfully.
10:28:01.845 | │ exit code: 1
10:28:01.845 | ╰─> [8 lines of output]
10:28:01.845 | Traceback (most recent call last):
10:28:01.845 | File "<string>", line 2, in <module>
10:28:01.845 | File "<pip-setuptools-caller>", line 34, in <module>
10:28:01.846 | File "/tmp/pip-install-9g1f79tv/python-javabridge_fc461e205f7f4afc87c818441711f35e/setup.py", line 412, in <module>
10:28:01.846 | ext_modules=ext_modules(),
10:28:01.846 | File "/tmp/pip-install-9g1f79tv/python-javabridge_fc461e205f7f4afc87c818441711f35e/setup.py", line 100, in ext_modules
10:28:01.846 | from numpy import get_include
10:28:01.846 | ModuleNotFoundError: No module named 'numpy'
10:28:01.846 | [end of output]
10:28:01.846 |  
10:28:01.847 | note: This error originates from a subprocess, and is likely not a problem with pip.
10:28:01.847 | error: metadata-generation-failed
10:28:01.847 |  
10:28:01.847 | × Encountered error while generating package metadata.
10:28:01.847 | ╰─> See above for output.
10:28:01.847 |  
10:28:01.847 | note: This is an issue with the package mentioned above, not pip.
10:28:01.848 | hint: See above for details.

**Comment by LeeKamentsky** [comment]
It looks like it is failing because Numpy isn't installed. Javabridge needs that to compile.If you can control the install order and make sure numpy is installed before javabridge that might help

**Comment by xanmankey** [comment]
In that case, I'm going to close this issue, because I feel like my problem relates more to installation via requirements.txt and my current implementation of installing dependencies for hosting on Vercel, and I don't want to stray too far from the original question about installation failures in Codespaces (although I'm still unsure why installing the library wasn't working in that environment). Maybe someone will have a similar issue, in which case I might continue to experiment with the installation in Codespaces, but for now I'd like to divert my attention to alternative methods and projects. I appreciate your comments though Lee, and I wish you the best of luck on getting your PyPi account reinstated!
